/// Liste des pays avec leur indicatif téléphonique et emoji drapeau.
/// Source : données ISO 3166-1 + ITU-T E.164
class CountryDialCode {
  final String name;
  final String flag;
  final String dialCode;
  final String code; // ISO 3166-1 alpha-2

  const CountryDialCode({
    required this.name,
    required this.flag,
    required this.dialCode,
    required this.code,
  });

  String get display => '$flag $dialCode';
}

class CountryDialCodes {
  static const List<CountryDialCode> list = [
    CountryDialCode(name: "Afghanistan", flag: "🇦🇫", dialCode: "+93", code: "AF"),
    CountryDialCode(name: "Afrique du Sud", flag: "🇿🇦", dialCode: "+27", code: "ZA"),
    CountryDialCode(name: "Albanie", flag: "🇦🇱", dialCode: "+355", code: "AL"),
    CountryDialCode(name: "Algérie", flag: "🇩🇿", dialCode: "+213", code: "DZ"),
    CountryDialCode(name: "Allemagne", flag: "🇩🇪", dialCode: "+49", code: "DE"),
    CountryDialCode(name: "Andorre", flag: "🇦🇩", dialCode: "+376", code: "AD"),
    CountryDialCode(name: "Angola", flag: "🇦🇴", dialCode: "+244", code: "AO"),
    CountryDialCode(name: "Arabie saoudite", flag: "🇸🇦", dialCode: "+966", code: "SA"),
    CountryDialCode(name: "Argentine", flag: "🇦🇷", dialCode: "+54", code: "AR"),
    CountryDialCode(name: "Arménie", flag: "🇦🇲", dialCode: "+374", code: "AM"),
    CountryDialCode(name: "Australie", flag: "🇦🇺", dialCode: "+61", code: "AU"),
    CountryDialCode(name: "Autriche", flag: "🇦🇹", dialCode: "+43", code: "AT"),
    CountryDialCode(name: "Azerbaïdjan", flag: "🇦🇿", dialCode: "+994", code: "AZ"),
    CountryDialCode(name: "Bahamas", flag: "🇧🇸", dialCode: "+1-242", code: "BS"),
    CountryDialCode(name: "Bahreïn", flag: "🇧🇭", dialCode: "+973", code: "BH"),
    CountryDialCode(name: "Bangladesh", flag: "🇧🇩", dialCode: "+880", code: "BD"),
    CountryDialCode(name: "Belgique", flag: "🇧🇪", dialCode: "+32", code: "BE"),
    CountryDialCode(name: "Bénin", flag: "🇧🇯", dialCode: "+229", code: "BJ"),
    CountryDialCode(name: "Bolivie", flag: "🇧🇴", dialCode: "+591", code: "BO"),
    CountryDialCode(name: "Bosnie-Herzégovine", flag: "🇧🇦", dialCode: "+387", code: "BA"),
    CountryDialCode(name: "Botswana", flag: "🇧🇼", dialCode: "+267", code: "BW"),
    CountryDialCode(name: "Brésil", flag: "🇧🇷", dialCode: "+55", code: "BR"),
    CountryDialCode(name: "Burkina Faso", flag: "🇧🇫", dialCode: "+226", code: "BF"),
    CountryDialCode(name: "Burundi", flag: "🇧🇮", dialCode: "+257", code: "BI"),
    CountryDialCode(name: "Cambodge", flag: "🇰🇭", dialCode: "+855", code: "KH"),
    CountryDialCode(name: "Cameroun", flag: "🇨🇲", dialCode: "+237", code: "CM"),
    CountryDialCode(name: "Canada", flag: "🇨🇦", dialCode: "+1", code: "CA"),
    CountryDialCode(name: "Cap-Vert", flag: "🇨🇻", dialCode: "+238", code: "CV"),
    CountryDialCode(name: "Chili", flag: "🇨🇱", dialCode: "+56", code: "CL"),
    CountryDialCode(name: "Chine", flag: "🇨🇳", dialCode: "+86", code: "CN"),
    CountryDialCode(name: "Chypre", flag: "🇨🇾", dialCode: "+357", code: "CY"),
    CountryDialCode(name: "Colombie", flag: "🇨🇴", dialCode: "+57", code: "CO"),
    CountryDialCode(name: "Comores", flag: "🇰🇲", dialCode: "+269", code: "KM"),
    CountryDialCode(name: "Congo", flag: "🇨🇬", dialCode: "+242", code: "CG"),
    CountryDialCode(name: "Corée du Sud", flag: "🇰🇷", dialCode: "+82", code: "KR"),
    CountryDialCode(name: "Côte d'Ivoire", flag: "🇨🇮", dialCode: "+225", code: "CI"),
    CountryDialCode(name: "Croatie", flag: "🇭🇷", dialCode: "+385", code: "HR"),
    CountryDialCode(name: "Cuba", flag: "🇨🇺", dialCode: "+53", code: "CU"),
    CountryDialCode(name: "Danemark", flag: "🇩🇰", dialCode: "+45", code: "DK"),
    CountryDialCode(name: "Djibouti", flag: "🇩🇯", dialCode: "+253", code: "DJ"),
    CountryDialCode(name: "Égypte", flag: "🇪🇬", dialCode: "+20", code: "EG"),
    CountryDialCode(name: "Émirats arabes unis", flag: "🇦🇪", dialCode: "+971", code: "AE"),
    CountryDialCode(name: "Équateur", flag: "🇪🇨", dialCode: "+593", code: "EC"),
    CountryDialCode(name: "Érythrée", flag: "🇪🇷", dialCode: "+291", code: "ER"),
    CountryDialCode(name: "Espagne", flag: "🇪🇸", dialCode: "+34", code: "ES"),
    CountryDialCode(name: "Estonie", flag: "🇪🇪", dialCode: "+372", code: "EE"),
    CountryDialCode(name: "Éthiopie", flag: "🇪🇹", dialCode: "+251", code: "ET"),
    CountryDialCode(name: "Fidji", flag: "🇫🇯", dialCode: "+679", code: "FJ"),
    CountryDialCode(name: "Finlande", flag: "🇫🇮", dialCode: "+358", code: "FI"),
    CountryDialCode(name: "France", flag: "🇫🇷", dialCode: "+33", code: "FR"),
    CountryDialCode(name: "Gabon", flag: "🇬🇦", dialCode: "+241", code: "GA"),
    CountryDialCode(name: "Gambie", flag: "🇬🇲", dialCode: "+220", code: "GM"),
    CountryDialCode(name: "Géorgie", flag: "🇬🇪", dialCode: "+995", code: "GE"),
    CountryDialCode(name: "Ghana", flag: "🇬🇭", dialCode: "+233", code: "GH"),
    CountryDialCode(name: "Grèce", flag: "🇬🇷", dialCode: "+30", code: "GR"),
    CountryDialCode(name: "Guatemala", flag: "🇬🇹", dialCode: "+502", code: "GT"),
    CountryDialCode(name: "Guinée", flag: "🇬🇳", dialCode: "+224", code: "GN"),
    CountryDialCode(name: "Guinée-Bissau", flag: "🇬🇼", dialCode: "+245", code: "GW"),
    CountryDialCode(name: "Guinée équatoriale", flag: "🇬🇶", dialCode: "+240", code: "GQ"),
    CountryDialCode(name: "Haïti", flag: "🇭🇹", dialCode: "+509", code: "HT"),
    CountryDialCode(name: "Honduras", flag: "🇭🇳", dialCode: "+504", code: "HN"),
    CountryDialCode(name: "Hongrie", flag: "🇭🇺", dialCode: "+36", code: "HU"),
    CountryDialCode(name: "Inde", flag: "🇮🇳", dialCode: "+91", code: "IN"),
    CountryDialCode(name: "Indonésie", flag: "🇮🇩", dialCode: "+62", code: "ID"),
    CountryDialCode(name: "Irak", flag: "🇮🇶", dialCode: "+964", code: "IQ"),
    CountryDialCode(name: "Iran", flag: "🇮🇷", dialCode: "+98", code: "IR"),
    CountryDialCode(name: "Irlande", flag: "🇮🇪", dialCode: "+353", code: "IE"),
    CountryDialCode(name: "Islande", flag: "🇮🇸", dialCode: "+354", code: "IS"),
    CountryDialCode(name: "Israël", flag: "🇮🇱", dialCode: "+972", code: "IL"),
    CountryDialCode(name: "Italie", flag: "🇮🇹", dialCode: "+39", code: "IT"),
    CountryDialCode(name: "Jamaïque", flag: "🇯🇲", dialCode: "+1-876", code: "JM"),
    CountryDialCode(name: "Japon", flag: "🇯🇵", dialCode: "+81", code: "JP"),
    CountryDialCode(name: "Jordanie", flag: "🇯🇴", dialCode: "+962", code: "JO"),
    CountryDialCode(name: "Kazakhstan", flag: "🇰🇿", dialCode: "+7", code: "KZ"),
    CountryDialCode(name: "Kenya", flag: "🇰🇪", dialCode: "+254", code: "KE"),
    CountryDialCode(name: "Koweït", flag: "🇰🇼", dialCode: "+965", code: "KW"),
    CountryDialCode(name: "Laos", flag: "🇱🇦", dialCode: "+856", code: "LA"),
    CountryDialCode(name: "Lesotho", flag: "🇱🇸", dialCode: "+266", code: "LS"),
    CountryDialCode(name: "Lettonie", flag: "🇱🇻", dialCode: "+371", code: "LV"),
    CountryDialCode(name: "Liban", flag: "🇱🇧", dialCode: "+961", code: "LB"),
    CountryDialCode(name: "Liberia", flag: "🇱🇷", dialCode: "+231", code: "LR"),
    CountryDialCode(name: "Libye", flag: "🇱🇾", dialCode: "+218", code: "LY"),
    CountryDialCode(name: "Lituanie", flag: "🇱🇹", dialCode: "+370", code: "LT"),
    CountryDialCode(name: "Luxembourg", flag: "🇱🇺", dialCode: "+352", code: "LU"),
    CountryDialCode(name: "Madagascar", flag: "🇲🇬", dialCode: "+261", code: "MG"),
    CountryDialCode(name: "Malawi", flag: "🇲🇼", dialCode: "+265", code: "MW"),
    CountryDialCode(name: "Maldives", flag: "🇲🇻", dialCode: "+960", code: "MV"),
    CountryDialCode(name: "Mali", flag: "🇲🇱", dialCode: "+223", code: "ML"),
    CountryDialCode(name: "Malte", flag: "🇲🇹", dialCode: "+356", code: "MT"),
    CountryDialCode(name: "Maroc", flag: "🇲🇦", dialCode: "+212", code: "MA"),
    CountryDialCode(name: "Maurice", flag: "🇲🇺", dialCode: "+230", code: "MU"),
    CountryDialCode(name: "Mauritanie", flag: "🇲🇷", dialCode: "+222", code: "MR"),
    CountryDialCode(name: "Mexique", flag: "🇲🇽", dialCode: "+52", code: "MX"),
    CountryDialCode(name: "Mozambique", flag: "🇲🇿", dialCode: "+258", code: "MZ"),
    CountryDialCode(name: "Namibie", flag: "🇳🇦", dialCode: "+264", code: "NA"),
    CountryDialCode(name: "Népal", flag: "🇳🇵", dialCode: "+977", code: "NP"),
    CountryDialCode(name: "Nicaragua", flag: "🇳🇮", dialCode: "+505", code: "NI"),
    CountryDialCode(name: "Niger", flag: "🇳🇪", dialCode: "+227", code: "NE"),
    CountryDialCode(name: "Nigeria", flag: "🇳🇬", dialCode: "+234", code: "NG"),
    CountryDialCode(name: "Norvège", flag: "🇳🇴", dialCode: "+47", code: "NO"),
    CountryDialCode(name: "Nouvelle-Zélande", flag: "🇳🇿", dialCode: "+64", code: "NZ"),
    CountryDialCode(name: "Oman", flag: "🇴🇲", dialCode: "+968", code: "OM"),
    CountryDialCode(name: "Ouganda", flag: "🇺🇬", dialCode: "+256", code: "UG"),
    CountryDialCode(name: "Ouzbékistan", flag: "🇺🇿", dialCode: "+998", code: "UZ"),
    CountryDialCode(name: "Pakistan", flag: "🇵🇰", dialCode: "+92", code: "PK"),
    CountryDialCode(name: "Panama", flag: "🇵🇦", dialCode: "+507", code: "PA"),
    CountryDialCode(name: "Paraguay", flag: "🇵🇾", dialCode: "+595", code: "PY"),
    CountryDialCode(name: "Pays-Bas", flag: "🇳🇱", dialCode: "+31", code: "NL"),
    CountryDialCode(name: "Pérou", flag: "🇵🇪", dialCode: "+51", code: "PE"),
    CountryDialCode(name: "Philippines", flag: "🇵🇭", dialCode: "+63", code: "PH"),
    CountryDialCode(name: "Pologne", flag: "🇵🇱", dialCode: "+48", code: "PL"),
    CountryDialCode(name: "Portugal", flag: "🇵🇹", dialCode: "+351", code: "PT"),
    CountryDialCode(name: "Qatar", flag: "🇶🇦", dialCode: "+974", code: "QA"),
    CountryDialCode(name: "République centrafricaine", flag: "🇨🇫", dialCode: "+236", code: "CF"),
    CountryDialCode(name: "République démocratique du Congo", flag: "🇨🇩", dialCode: "+243", code: "CD"),
    CountryDialCode(name: "République dominicaine", flag: "🇩🇴", dialCode: "+1-809", code: "DO"),
    CountryDialCode(name: "Roumanie", flag: "🇷🇴", dialCode: "+40", code: "RO"),
    CountryDialCode(name: "Royaume-Uni", flag: "🇬🇧", dialCode: "+44", code: "GB"),
    CountryDialCode(name: "Russie", flag: "🇷🇺", dialCode: "+7", code: "RU"),
    CountryDialCode(name: "Rwanda", flag: "🇷🇼", dialCode: "+250", code: "RW"),
    CountryDialCode(name: "Saint-Kitts-et-Nevis", flag: "🇰🇳", dialCode: "+1-869", code: "KN"),
    CountryDialCode(name: "Sao Tomé-et-Principe", flag: "🇸🇹", dialCode: "+239", code: "ST"),
    CountryDialCode(name: "Sénégal", flag: "🇸🇳", dialCode: "+221", code: "SN"),
    CountryDialCode(name: "Serbie", flag: "🇷🇸", dialCode: "+381", code: "RS"),
    CountryDialCode(name: "Sierra Leone", flag: "🇸🇱", dialCode: "+232", code: "SL"),
    CountryDialCode(name: "Singapour", flag: "🇸🇬", dialCode: "+65", code: "SG"),
    CountryDialCode(name: "Slovaquie", flag: "🇸🇰", dialCode: "+421", code: "SK"),
    CountryDialCode(name: "Slovénie", flag: "🇸🇮", dialCode: "+386", code: "SI"),
    CountryDialCode(name: "Somalie", flag: "🇸🇴", dialCode: "+252", code: "SO"),
    CountryDialCode(name: "Soudan", flag: "🇸🇩", dialCode: "+249", code: "SD"),
    CountryDialCode(name: "Soudan du Sud", flag: "🇸🇸", dialCode: "+211", code: "SS"),
    CountryDialCode(name: "Sri Lanka", flag: "🇱🇰", dialCode: "+94", code: "LK"),
    CountryDialCode(name: "Suède", flag: "🇸🇪", dialCode: "+46", code: "SE"),
    CountryDialCode(name: "Suisse", flag: "🇨🇭", dialCode: "+41", code: "CH"),
    CountryDialCode(name: "Syrie", flag: "🇸🇾", dialCode: "+963", code: "SY"),
    CountryDialCode(name: "Taïwan", flag: "🇹🇼", dialCode: "+886", code: "TW"),
    CountryDialCode(name: "Tanzanie", flag: "🇹🇿", dialCode: "+255", code: "TZ"),
    CountryDialCode(name: "Tchad", flag: "🇹🇩", dialCode: "+235", code: "TD"),
    CountryDialCode(name: "Thaïlande", flag: "🇹🇭", dialCode: "+66", code: "TH"),
    CountryDialCode(name: "Togo", flag: "🇹🇬", dialCode: "+228", code: "TG"),
    CountryDialCode(name: "Trinité-et-Tobago", flag: "🇹🇹", dialCode: "+1-868", code: "TT"),
    CountryDialCode(name: "Tunisie", flag: "🇹🇳", dialCode: "+216", code: "TN"),
    CountryDialCode(name: "Turquie", flag: "🇹🇷", dialCode: "+90", code: "TR"),
    CountryDialCode(name: "Ukraine", flag: "🇺🇦", dialCode: "+380", code: "UA"),
    CountryDialCode(name: "Uruguay", flag: "🇺🇾", dialCode: "+598", code: "UY"),
    CountryDialCode(name: "Venezuela", flag: "🇻🇪", dialCode: "+58", code: "VE"),
    CountryDialCode(name: "Vietnam", flag: "🇻🇳", dialCode: "+84", code: "VN"),
    CountryDialCode(name: "Yémen", flag: "🇾🇪", dialCode: "+967", code: "YE"),
    CountryDialCode(name: "Zambie", flag: "🇿🇲", dialCode: "+260", code: "ZM"),
    CountryDialCode(name: "Zimbabwe", flag: "🇿🇼", dialCode: "+263", code: "ZW"),
    // Pays francophones importants en priorité (Côte d'Ivoire par défaut)
    CountryDialCode(name: "États-Unis", flag: "🇺🇸", dialCode: "+1", code: "US"),
  ];

  /// Retourne le pays par défaut (Côte d'Ivoire)
  static CountryDialCode get defaultCountry =>
      list.firstWhere((c) => c.code == "CI");

  /// Recherche un pays par son code ISO
  static CountryDialCode? findByCode(String code) {
    try {
      return list.firstWhere((c) => c.code == code);
    } catch (_) {
      return null;
    }
  }
}
